---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}-nginx
spec:
  selector:
    matchLabels:
      run: {{ .Name }}-nginx
  replicas: {{ .Params.DEPLOYMENT_REPLICAS }}
  template:
    metadata:
      labels:
        run: {{ .Name }}-nginx
    spec:
      containers:
      - name: {{ .Name }}-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: {{ .Params.NGX_MEMORY }}
            cpu: {{ .Params.NGX_CPUS }}
          limits:
            memory: {{ .Params.NGX_MEM_LIMIT }}
            cpu: {{ .Params.NGX_CPUS_LIMIT }}
